// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  card_list: dynamic(() => import("./CardList")),
  color_stop: dynamic(() => import("./ColorStop")),
  contact_form: dynamic(() => import("./ContactForm")),
  hero: dynamic(() => import("./Hero")),
  image_and_text: dynamic(() => import("./ImageAndText")),
  navigation_item: dynamic(() => import("./NavigationItem")),
  text: dynamic(() => import("./Text")),
};
